[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/_health"
healthcheckTimeout = 1000
port = 1337

[variables]
NODE_VERSION = "20"
NODE_ENV = "production"
PUBLIC_URL = "https://${RAILWAY_STATIC_URL}"